import math
from typing import Iterable, List

import pandas as pd

def amazon_dominance_flag(row: pd.Series) -> bool:
    """Return True if Amazon is likely dominating the listing.

    Conditions:
    - bb_amz_pct_30d >= 50
    - amz_availability contains 'in stock'
    - amz_now is not NA
    """
    amz_pct = pd.to_numeric(row.get("bb_amz_pct_30d"), errors="coerce")
    availability = str(row.get("amz_availability", "")).lower()
    amz_now = row.get("amz_now")
    return bool(
        (pd.notna(amz_pct) and amz_pct >= 50)
        or ("in stock" in availability)
        or pd.notna(amz_now)
    )


def competition_score(row: pd.Series) -> float:
    """Calculate a simple competition score based on offers and buy box winners.

    Both metrics are normalised to [0,1] with a cap at 50 to avoid
    extreme influence.
    """
    offers = pd.to_numeric(row.get("offer_new_now"), errors="coerce")
    winners = pd.to_numeric(row.get("bb_winners_30d"), errors="coerce")
    offers_norm = min(max(offers, 0), 50) / 50 if pd.notna(offers) else 0.0
    winners_norm = min(max(winners, 0), 50) / 50 if pd.notna(winners) else 0.0
    return float((offers_norm + winners_norm) / 2)


def best_cross_market_combo(
    df: pd.DataFrame,
    sell_targets: Iterable[str],
    min_pct: float = 0.0,
    min_volume: float = 0.0,
    max_offers: int | None = None,
) -> pd.DataFrame:
    """Return best buy/sell combination per ASIN.

    Parameters
    ----------
    df:
        Input DataFrame. It is expected to contain the columns generated by the
        main application, namely ``ASIN``, ``Title (base)``, ``Locale (base)``,
        ``Locale (comp)``, ``net_eur`` and ``net_pct`` together with demand and
        competition metrics.
    sell_targets:
        Iterable of locale codes that are valid selling markets.
    min_pct:
        Minimum net percentage required for a combo to be considered.
    min_volume:
        Minimum ``bought_30d`` (proxy for volume) required for the selling
        market.
    max_offers:
        Optional cap on ``offer_new_now`` for the selling market.

    Returns
    -------
    pd.DataFrame
        One row per ASIN with the best buy/sell combination. The returned
        columns are ``asin``, ``title``, ``best_buy_locale``,
        ``best_sell_locale``, ``net_eur``, ``net_pct``, ``rank_now``,
        ``bought_30d``, ``offer_new_now`` and ``score_v2``.
    """

    columns = [
        "asin",
        "title",
        "best_buy_locale",
        "best_sell_locale",
        "net_eur",
        "net_pct",
        "rank_now",
        "bought_30d",
        "offer_new_now",
        "score_v2",
    ]

    if df is None or df.empty:
        return pd.DataFrame(columns=columns)

    sell_targets = {str(s).upper() for s in sell_targets}

    # Normalise common column names used by the application.
    renames = {
        "ASIN": "asin",
        "Title (base)": "title",
        "Locale (base)": "buy_locale",
        "Locale (comp)": "sell_locale",
        "SalesRank_Comp": "rank_now",
        "Bought_Comp": "bought_30d",
        "NewOffer_Comp": "offer_new_now",
        "Opportunity_Score": "score_v2",
    }
    df = df.rename(columns={k: v for k, v in renames.items() if k in df.columns})

    if "sell_locale" not in df.columns or "buy_locale" not in df.columns:
        # Single locale case: simply return the first row using provided cost
        # basis. We assume ``locale`` column identifies the market.
        loc_col = "locale"
        if loc_col not in df.columns:
            for c in ["buy_locale", "sell_locale", "Locale", "market"]:
                if c in df.columns:
                    loc_col = c
                    break
        row = df.iloc[0]
        locale = row.get(loc_col)
        sale_price = pd.to_numeric(row.get("sale_price") or row.get("sale_price_used"), errors="coerce")
        cost_basis = pd.to_numeric(row.get("purchase_price"), errors="coerce")
        net_eur = float(sale_price) - float(cost_basis)
        net_pct = (100.0 * net_eur / cost_basis) if cost_basis else math.nan
        return pd.DataFrame(
            [
                {
                    "asin": row.get("asin"),
                    "title": row.get("title"),
                    "best_buy_locale": locale,
                    "best_sell_locale": locale,
                    "net_eur": net_eur,
                    "net_pct": net_pct,
                    "rank_now": row.get("rank_now"),
                    "bought_30d": row.get("bought_30d"),
                    "offer_new_now": row.get("offer_new_now"),
                    "score_v2": row.get("score_v2"),
                }
            ],
            columns=columns,
        )

    # Multi locale: evaluate all combinations and pick best per ASIN.
    df = df.copy()
    results: List[dict] = []
    for asin, grp in df.groupby("asin"):
        combos: List[dict] = []
        for _, buy in grp.iterrows():
            buy_price = pd.to_numeric(buy.get("purchase_price"), errors="coerce")
            buy_locale = str(buy.get("buy_locale"))
            if not math.isfinite(buy_price) or buy_price <= 0:
                continue
            for _, sell in grp.iterrows():
                sell_locale = str(sell.get("sell_locale")).upper()
                if sell_locale not in sell_targets:
                    continue
                sale_price = pd.to_numeric(
                    sell.get("sale_price") or sell.get("sale_price_used"),
                    errors="coerce",
                )
                net_eur = float(sale_price) - float(buy_price)
                net_pct = (100.0 * net_eur / buy_price) if buy_price else math.nan

                volume = pd.to_numeric(sell.get("bought_30d"), errors="coerce")
                offers = pd.to_numeric(sell.get("offer_new_now"), errors="coerce")

                if math.isfinite(net_pct) and net_pct < min_pct:
                    continue
                if math.isfinite(volume) and volume < min_volume:
                    continue
                if (
                    max_offers is not None
                    and math.isfinite(offers)
                    and offers > max_offers
                ):
                    continue

                combos.append(
                    {
                        "asin": asin,
                        "title": sell.get("title") or buy.get("title"),
                        "best_buy_locale": buy_locale,
                        "best_sell_locale": sell_locale,
                        "net_eur": net_eur,
                        "net_pct": net_pct,
                        "rank_now": sell.get("rank_now"),
                        "bought_30d": volume,
                        "offer_new_now": offers,
                        "score_v2": sell.get("score_v2"),
                    }
                )

        if combos:
            best = max(combos, key=lambda r: r["net_eur"])
            results.append(best)

    return pd.DataFrame(results, columns=columns)
